version: '3.7'

services:
  api:
    image: docker.pkg.github.com/chiel/food/api:dev-latest
    env_file: packages/api/.env
    ports:
      - 9153:9153
    volumes:
      - .:/opt/project

  app:
    image: docker.pkg.github.com/chiel/food/app:dev-latest
    env_file: packages/app/.env
    ports:
      - 9152:9152
    volumes:
      - .:/opt/project

  postgres:
    image: postgres:12.0-alpine
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: food
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
