---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: food-api
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
  tls:
    - hosts:
        - api.food.kunkels.me
      secretName: api-food-kunkels-me-tls
  rules:
    - host: api.food.kunkels.me
      http:
        paths:
          - backend:
              serviceName: food-api
              servicePort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: food-api
spec:
  selector:
    app: food-api
  ports:
    - name: http
      port: 80
      targetPort: 9153

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: food-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: food-api
    spec:
      imagePullSecrets:
        - name: docker.pkg.github.com
      containers:
        - name: api
          image: docker.pkg.github.com/chiel/food/api:${GITHUB_SHA}
