---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: food-app
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
  tls:
    - hosts:
        - food.kunkels.me
      secretName: food-kunkels-me-tls
  rules:
    - host: food.kunkels.me
      http:
        paths:
          - backend:
              serviceName: food-app
              servicePort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: food-app
spec:
  selector:
    app: food-app
  ports:
    - name: http
      port: 80
      targetPort: 9152

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: food-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: food-app
    spec:
      imagePullSecrets:
        - name: docker.pkg.github.com
      containers:
        - name: app
          image: docker.pkg.github.com/chiel/food/app:${GITHUB_SHA}
