name: CI

on:
  push:
    branches:
      - master

env:
  DOCKER_REPO: docker.pkg.github.com/chiel/food

jobs:
  docker-lint:
    name: Lint Dockerfiles
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Lint Dockerfiles
        uses: docker://hadolint/hadolint:latest-debian
        with:
          entrypoint: hadolint
          args: packages/app/Dockerfile

  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Cache node modules
        uses: actions/cache@v1
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.OS }}-dependencies-${{ hashFiles('yarn.lock') }}
      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: yarn

  build:
    name: Build app
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v1
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-dependencies-${{ hashFiles('yarn.lock') }}
      - name: Build app
        run: 'cd packages/app && yarn build'
      - uses: actions/upload-artifact@master
        with:
          name: build
          path: packages/app/dist

  docker-build:
    name: Build app Dockerfile
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@master
      - uses: actions/download-artifact@master
        with:
          name: build
          path: packages/app/dist
      - name: Build the image
        env:
          DOCKER_BUILDKIT: 1
        run: docker build --target prod -t $DOCKER_REPO/app:$GITHUB_SHA packages/app
      - name: Login to GPR
        run: |
          echo "${{ secrets.REGISTRY_TOKEN }}" | \
          docker login docker.pkg.github.com \
            -u "${{ secrets.REGISTRY_USER }}" \
            --password-stdin
      - name: Push image to GPR
        run: docker push $DOCKER_REPO/app:$GITHUB_SHA
